### ISSUE TITLE
Support connecting to Fully REST interface via SSL 

### ISSUE THREAD

**Issue by crowbarz** [cgarwood/python-fullykiosk#8]
Fully Kiosk supports connections via https using an SSL certificate as described in https://www.fully-kiosk.com/en/#remoteadmin . It would be useful for this package (as well as the HA integration) to support SSL encrypted sessions to the tablet, with an option to allow SSL self-signed certificates to be used. Right now, it looks like the library supports http connections only, and doesn't work if Fully is configured to use an SSL certificate.

**Comment by cgarwood** [comment]
Implemented in https://github.com/cgarwood/python-fullykiosk/pull/14  - published as version 0.0.12
